spring.application.name: Bhxd
server.port: 6021
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    # 密钥 820916ef951cba27
    url: jdbc:p6spy:mysql://localhost:3306/bhxd?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: x851942673
  jpa:
    hibernate:
      ddl-auto: update # 考虑生产环境中使用validate或none
    show-sql: true
    properties:
      hibernate:
  data:
    redis:
      host: 192.168.188.1
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 100ms
  security:
    password:
      encoder: bcrypt

# application.yml



mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: enabled
      logic-delete-value: 0
      logic-not-delete-value: 1

logging:
  level:
    com.p6spy: DEBUG
    #spring:
    #  datasource:
    #    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #    url: jdbc:p6spy:h2:mem:test
    # 其他数据库配置...
#      schema-locations: classpath:sql/user_account.sql
#      mode: always
#打印sql语句日志
